### ISSUE TITLE
Inner functions support

### ISSUE THREAD

**Issue by eniac314** [amenzwa/pfd#1]
You said in the readme than elm does not support nested inner functions. 

Is this not what you are talking about?
```
outerfunction : Int -> Int
outerfunction a =
    let
        innerFunction : Int -> Int
        innerFunction b =
            a + b
    in
    innerFunction 3
```
This is valid elm.

**Comment by amenzwa** [comment]
This is what I am talking about. I will fix my readme and my PFD code,
immediately. I'll notify you once I've completed my mistakes.

Thank you very much for pointing out my mistake. Saying a wrong thing about
Elm is the last thing I want to do when I'm trying to promote Elm.

**Comment by amenzwa** [comment]
I've removed my mistaken gripe in the README about Elm's lack of inner
functions. I'm updating my code, too. Again, thank you.

**Comment by eniac314** [comment]
Great! :)
