### ISSUE TITLE
Queue.LfrQueue - unexpected size after adding same item twice

### ISSUE THREAD

**Issue by Janiczek** [amenzwa/pfd#3]
I'm not sure this is expected (are you not allowed to enqueue the same item twice?)

Minimal example:
```elm
empty |> enq 0 |> enq 0 |> size
--> 3
```

Trying it out in `elm-repl`:

```elm
> import Queue.LfrQueue exposing (..)
> empty |> enq 0 |> enq 0 |> size
3 : Int
> empty |> enq 0 |> enq 0
([0],[0,0]) : Queue number
>
```

The test that found this:
```elm
fuzz (Fuzz.list Fuzz.int) "empty+enq+size: behaves like stdlib queue" <|
    \items ->
        let
            lfrQueue =
                List.foldl enq empty items

            stdlibQueue =
                List.foldl (::) [] items
        in
        size lfrQueue
            |> Expect.equal (List.length stdlibQueue)
```

**Comment by Janiczek** [comment]
I'm guessing this should use front and rear once each instead of using front twice 
https://github.com/amenzwa/pfd/blob/main/src/Queue/LfrQueue.elm#L34

**Comment by amenzwa** [comment]
Martin, Okasaki's Standard ML implementation for left-right queue (which he calls BatchedQueue) on p.43 is ` fun snoc ((f, r), x) = checkf (f, x::r)`, which I mistranslated into Elm as `enq x ( f, r ) = checkF ( f, x :: f )`. The correct translation is `enq x ( f, r ) = checkF ( f, x :: r )`. I just fixed this bug, and updated the test case, too.

Thank you so much for finding this bug.
